// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskiesBlazor.Model;

namespace TaskiesBlazor.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191001225348_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-rc1.19456.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskiesBlazor.Data.TaskBlock", b =>
                {
                    b.Property<int>("idTaskBlock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("coColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deTaskBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dtModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("bit");

                    b.Property<byte>("order")
                        .HasColumnType("tinyint");

                    b.HasKey("idTaskBlock");

                    b.ToTable("ToDoBlock");
                });

            modelBuilder.Entity("TaskiesBlazor.Data.Taskie", b =>
                {
                    b.Property<int>("idTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("deTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dtModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idParent")
                        .HasColumnType("int");

                    b.Property<int>("idTaskBlock")
                        .HasColumnType("int");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("bit");

                    b.HasKey("idTask");

                    b.HasIndex("idParent");

                    b.HasIndex("idTaskBlock");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("TaskiesBlazor.Data.Taskie", b =>
                {
                    b.HasOne("TaskiesBlazor.Data.Taskie", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("idParent");

                    b.HasOne("TaskiesBlazor.Data.TaskBlock", "TaskBlock")
                        .WithMany("Tasks")
                        .HasForeignKey("idTaskBlock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
